redirects:
- from: https://github.com/LuceliaMarques/teste/blob/master/.github/ISSUE_TEMPLATE/feature_request.yml
  to: https://github.com/LuceliaMarques/test/blob/master/.github/ISSUE_TEMPLATE/feature_request.yml
