# Please switch to **Preview** and select one of the following links:

# * [Feature](?template=https://github.com/LuceliaMarques/test/blob/master/.github/ISSUE_TEMPLATE/feature_request.yml)
# * [Bug](?template=https://github.com/LuceliaMarques/test/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml)
