name: Add bugs to bugs project
on: 
  schedule: 
  - cron: "10 14 * * *" 
permissions:
  issues: write
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/users/LuceliaMarques/projects/2
          github-token: ${{ secrets.ADD_PROJECT }}
          labeled: bug, cse
          label-operator: OR
