name: 'Label issue'
on: [push]
permissions: 
  contents: read-all|write-all
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7.0.0
        with:
          stale-issue-message: 'Stale issue obsoleto message'
          stale-issue-label: 'no-issue-activity'
          days-before-issue-stale: 1
          # exempt-issue-labels: 'awaiting-approval, work-in-progress'
          # only-labels: 'awaiting-feedback, awaiting-answers'