#name workflow
name: "Obsoleto label issues"

#agendar o evento
on: 
  schedule: 
  #especifica a hora do dia em que o fluxo será executado
  - cron: "55 8 * * 1-5" #runs at 7:00 a.m on every day-of-week from Monday through Friday

jobs: 
  stale: # Run-npm-on-Ubuntu: 
    runs-on: ubuntu-latest #etapa
    steps: 
    - uses: actions/stale@v7.0.0 #to check the stale
    with: 
      stale-issue-label: 'creation' #nome da label a ser criada
      stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
      days-before-issue-stale: 1 #período de tempo de criação: 60 days
     # labels-to-add-when-unstale: 'creation'
  
    permissions: read | write #trabalho a ser executado
    
#     only-labels:
#     only-issue-labels:  #com todos os x rotulos
#     any-of-labels: #com um desses rotulos
#     any-of-issue-labels: #substitui um dos rotulos

#     labels-to-add-when-unstale: #Adicione rótulos específicos de problemas/PRs quando eles se tornarem obsoletos

# only-labels:
#     only-issue-labels: 
#     any-of-labels:
#     any-of-issue-labels
